warning_threshold: 1

disabled_rules: # rule identifiers to exclude from running
  - switch_case_alignment # нужно посмотреть что это
  - empty_enum_arguments # нужно посмотреть что это
  - class_delegate_protocol # нужно посмотреть что это
  - for_where # нужно посмотреть нужно ли это нам
  - control_statement # нужно посмотреть нужно ли это нам
  - implicit_getter # нужно посмотреть нужно ли это нам

  - todo # пока игнорим

  - identifier_name # не нужно
  - shorthand_operator # не нужно
  - large_tuple # не нужно
  - trailing_comma # не использовать одну из фич Swift глупо

opt_in_rules:
  - anyobject_protocol
 
included:
  - ../Example/
  - ../NeoSkeuomorphKit/

function_body_length:
  warning: 60
  error: 120
file_length:
  warning: 500
  error: 500
line_length:
  warning: 120
  error: 120
type_name:
  excluded: T
  max_length:
    warning: 56
function_parameter_count:
  warning: 7
